# Generated by Django 3.1.3 on 2020-12-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='postdata',
            new_name='postdate',
        ),
    ]
